runtime: python39

beta_settings:
  cloud_sql_instances: ux360-1:us-central1:task-logger-db
  
env_variables:
  DB_NAME: "task_logger"
  DB_SOCKET: "/cloudsql/ux360-1:us-central1:task-logger-db"
  DB_PSWD: "password"
  DB_USER: "root"
