runtime: python39

beta_settings:
  cloud_sql_instances: ux360-14:us-central1:lamp-mysql-db
  
env_variables:
  DB_NAME: "task_logger"
  DB_SOCKET: "/cloudsql/ux360-14:us-central1:lamp-mysql-db"
  DB_PSWD: "yar"
  DB_USER: "mysql-testpass-123"
